// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// pulse //
// ----- //

#define pulse_wrap_target 0
#define pulse_wrap 3

#define pulse_CLOCK 2000000

static const uint16_t pulse_program_instructions[] = {
	//     .wrap_target
	0xfd00, //  0: set    pins, 0                [29]
	0xbd42, //  1: nop                           [29]
	0xe001, //  2: set    pins, 1
	0x0003, //  3: jmp    3
	//     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulse_program = {
	.instructions = pulse_program_instructions,
	.length = 4,
	.origin = -1,
};

static inline pio_sm_config pulse_program_get_default_config(uint offset) {
	pio_sm_config c = pio_get_default_sm_config();
	sm_config_set_wrap(&c, offset + pulse_wrap_target, offset + pulse_wrap);
	return c;
}
#endif
