// Minimal stub for generated ML model header
// This allows building when the real `model.h` (generated by the ML exporter)
// is not present. Replace with the real generated header for actual inference.

#ifndef SRC_MODEL_H
#define SRC_MODEL_H

namespace Eloquent {
namespace ML {
namespace Port {

class EloquentML {
public:
    EloquentML() {}
    // features: pointer to float features array. Return 0/1 as class label.
    inline int predict(const float *features) {
        (void)features; // unused in stub
        return 0; // default: no pre-fire
    }
};

} // namespace Port
} // namespace ML
} // namespace Eloquent

#endif // SRC_MODEL_H
